
project_id = "qaeqzmsxcpnrnbwccrzg"

[functions.send-confirmation]
verify_jwt = false

[functions.send-whatsapp-confirmation]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.generate-daily-love-letter]
verify_jwt = false

[functions.send-daily-love-letters]
verify_jwt = false
